#include "test.hpp"
#include "life/world.hpp"
using namespace life;
TEST("social", conversation_has_nested_content) {
    auto w=World::generate(42,8);auto& s=w.edit_for_test();
    s.autonomy=false;s.actors[0].place=s.actors[1].place=2;
    s.actors[0].social=s.actors[1].social=.3;
    bool nested=false;
    w.set_thought_logger([&](const Thought& t){if(t.detail.starts_with("social_"))nested=true;});
    w.command_for_test(1,Method::Talk,2);s.autonomy=true;
    w.run_seconds(120);
    CHECK(nested);
}
#include <filesystem>
#include <set>
#include <algorithm>
namespace {
std::size_t sk(Interaction k){return std::size_t(k);}
World scene(const char* name){auto w=World::generate(42,8);w.configure_social_scene(name);return w;}
std::uint64_t completions(const World& w,Interaction k){return w.state().social.completed[sk(k)];}
}
TEST("social", autonomous_friendly_touch_survives_personal_romance_norm){auto w=scene("friendly");w.run_seconds(120);CHECK(completions(w,Interaction::FriendlyTouch)>0);CHECK(completions(w,Interaction::RomanticTouch)==0);CHECK(w.state().actors[0].mind.social.learned_outcomes>0);}
TEST("social", same_gender_contact_is_possible_in_neutral_profile){auto w=scene("romantic");w.run_seconds(120);CHECK(completions(w,Interaction::RomanticTouch)>0);CHECK(w.state().actors[0].mind.social.gender==w.state().actors[1].mind.social.gender);}
TEST("social", own_finite_norm_changes_autonomous_choice){auto a=scene("romantic"),b=scene("romantic-norm");a.run_seconds(120);b.run_seconds(120);CHECK(completions(a,Interaction::RomanticTouch)>0);CHECK(completions(b,Interaction::RomanticTouch)==0);for(auto& e:b.state().social.events)CHECK(e.initiator!=1);}
TEST("social", receiver_refusal_prevents_contact_effect){auto w=scene("recipient-refuses");w.run_seconds(120);CHECK(w.state().social.declined[sk(Interaction::RomanticTouch)]>0);CHECK(completions(w,Interaction::RomanticTouch)==0);CHECK(w.state().social.accepted[sk(Interaction::RomanticTouch)]==0);}
TEST("social", private_receiver_norm_not_leaked_in_requester_forecast){auto a=scene("romantic"),b=scene("recipient-refuses");const auto x=a.personal_view(1),y=b.personal_view(1);auto p=PlanOption{Method::Social,2,2,.9};p.interaction=Interaction::RomanticTouch;NEAR(Planner::forecast(x,p).score,Planner::forecast(y,p).score,1e-12);}
TEST("social", real_pleasantness_can_disagree_with_expected_pleasantness){auto w=scene("pleasure-mismatch");const auto prior=w.state().actors[0].mind.social.methods[sk(Interaction::RomanticTouch)].expected_pleasure;CHECK(prior>0);w.run_seconds(120);const auto& m=w.state().actors[0].mind.social;auto* e=m.experience(Interaction::RomanticTouch,2,0,false);CHECK(e&&e->pleasure.mean<0);CHECK(m.methods[sk(Interaction::RomanticTouch)].expected_pleasure==prior);}
TEST("social", nested_interaction_does_not_cancel_parent_conversation){auto w=scene("friendly");const auto parent=w.state().actors[0].action.id;w.run_seconds(25);CHECK(completions(w,Interaction::FriendlyTouch)>0);CHECK(w.state().actors[0].action.method==Method::Talk);CHECK(w.state().actors[0].action.id==parent);CHECK(w.state().actors[1].action.id==parent);}
TEST("social", proposal_cannot_complete_before_receiver_thinks){auto w=scene("friendly");w.propose_social_for_test(1,Interaction::FriendlyTouch,2);CHECK(w.state().social.events.size()==1);CHECK(w.state().social.events[0].phase==SocialPhase::Proposed);w.run_ms(100);CHECK(w.state().social.events[0].phase==SocialPhase::Proposed);CHECK(completions(w,Interaction::FriendlyTouch)==0);}
TEST("social", consent_scope_cannot_be_replaced_with_another_action){auto w=scene("friendly");w.propose_social_for_test(1,Interaction::FriendlyTouch,2);auto id=w.state().social.events.back().id;w.propose_social_for_test(1,Interaction::RomanticTouch,2);CHECK(w.state().social.events.size()==1&&w.state().social.events.back().id==id);CHECK(w.state().social.events.back().kind==Interaction::FriendlyTouch);}
TEST("social", withdrawal_before_answer_has_no_completed_effect){auto w=scene("friendly");w.propose_social_for_test(1,Interaction::FriendlyTouch,2);auto id=w.state().social.events.back().id;w.withdraw_social_for_test(1);w.edit_for_test().actors[0].mind.social.methods[0].mastery=0;w.edit_for_test().actors[1].mind.social.methods[0].mastery=0;w.run_seconds(30);CHECK(w.state().social.events[0].id==id);CHECK(w.state().social.events[0].phase==SocialPhase::Cancelled);CHECK(completions(w,Interaction::FriendlyTouch)==0);}
TEST("social", stopped_parent_invalidates_pending_proposal){auto w=scene("friendly");w.propose_social_for_test(1,Interaction::FriendlyTouch,2);w.command_for_test(1,Method::Leisure,2);w.run_seconds(30);CHECK(w.state().social.events[0].phase==SocialPhase::Cancelled);const auto oldparent=w.state().social.events[0].parent;for(const auto&e:w.state().social.events)CHECK(e.parent!=oldparent||e.phase!=SocialPhase::Completed);}
TEST("social", process_pause_does_not_republish_old_result){auto a=scene("friendly"),b=a;a.run_ms(120000);for(int i=0;i<1200;++i)b.run_ms(100);CHECK(a.hash()==b.hash());}
TEST("social", nested_save_before_answer_preserves_future){auto a=scene("friendly");a.propose_social_for_test(1,Interaction::FriendlyTouch,2);a.run_ms(100);const auto path=(std::filesystem::temp_directory_path()/"life-social-offer.save").string();a.save(path);auto b=World::load(path);a.run_ms(119900);b.run_ms(119900);CHECK(a.hash()==b.hash());std::filesystem::remove(path);}
TEST("social", nested_save_after_consent_preserves_future){auto a=scene("friendly");a.propose_social_for_test(1,Interaction::FriendlyTouch,2);for(int n=0;n<60&&a.state().social.events[0].phase!=SocialPhase::Accepted;++n)a.run_ms(100);CHECK(a.state().social.events[0].phase==SocialPhase::Accepted);auto path=(std::filesystem::temp_directory_path()/"life-social-accepted.save").string();a.save(path);auto b=World::load(path);a.run_seconds(120);b.run_seconds(120);CHECK(a.hash()==b.hash());std::filesystem::remove(path);}
TEST("social", social_workers_preserve_exact_thoughts){auto a=scene("borrow"),b=a;b.set_workers(4,2);std::vector<std::string>x,y;a.set_thought_logger([&](const auto&t){x.push_back(thought_json(t));});b.set_thought_logger([&](const auto&t){y.push_back(thought_json(t));});a.run_seconds(900);b.run_seconds(900);CHECK(a.hash()==b.hash());CHECK(x==y);}
TEST("social", social_index_matches_reference){auto a=scene("borrow"),b=a;b.set_indexed(false);a.run_seconds(900);b.run_seconds(900);CHECK(a.hash()==b.hash());}
TEST("social", social_logging_cannot_change_learning){auto a=scene("friendly"),b=a;std::uint64_t rows=0;b.set_logger([&](const auto&){++rows;});b.set_thought_logger([&](const auto&){++rows;});a.run_seconds(120);b.run_seconds(120);CHECK(rows>0);CHECK(a.hash()==b.hash());}
TEST("social", full_information_borrow_use_return_chain){auto w=scene("borrow");w.run_seconds(900);CHECK(completions(w,Interaction::AskInfo)==1);CHECK(completions(w,Interaction::BorrowItem)==1);CHECK(completions(w,Interaction::UseItem)>=2);CHECK(completions(w,Interaction::ReturnItem)==1);const auto& objects=w.state().social.objects;auto it=std::find_if(objects.begin(),objects.end(),[](auto&o){return o.id==2000;});CHECK(it!=objects.end()&&it->owner==2&&it->holder==2&&it->active_loan==0);CHECK(w.state().social.loans.size()==1&&w.state().social.loans[0].returned);w.validate();}
TEST("social", text_experience_unlocks_known_method_without_fake_practice){auto w=scene("borrow");CHECK(w.state().actors[0].mind.social.methods[sk(Interaction::Compliment)].mastery<.6);w.run_seconds(900);const auto& m=w.state().actors[0].mind.social;CHECK(m.methods[sk(Interaction::Compliment)].mastery>=.6);CHECK(m.items.size()>0&&m.item(2000)->uses>=2);CHECK(w.state().social.completed[sk(Interaction::Compliment)]==0);}
TEST("social", information_answer_comes_from_personal_memory_not_world_truth){auto w=scene("information");auto& s=w.edit_for_test();auto it=std::find_if(s.social.objects.begin(),s.social.objects.end(),[](auto&o){return o.id==2000;});it->owner=3;w.run_seconds(120);const auto* belief=w.state().actors[0].mind.social.item(2000);CHECK(belief&&belief->owner==2&&belief->origin==FactOrigin::Reported);CHECK(it->owner==3);}
TEST("social", uninvolved_actor_does_not_receive_private_object_information){auto w=scene("information");CHECK(!w.state().actors[2].mind.social.item(2000));w.run_seconds(120);CHECK(!w.state().actors[2].mind.social.item(2000));}
TEST("social", high_honesty_norm_blocks_false_status_claim_not_physics){auto a=scene("status"),b=scene("status-norm");a.run_seconds(300);b.run_seconds(300);bool low=false,high=false;for(const auto&e:a.state().social.events)low|=e.initiator==1&&e.object==2000&&e.phase==SocialPhase::Completed;for(const auto&e:b.state().social.events)high|=e.initiator==1&&e.object==2000&&e.phase==SocialPhase::Completed;CHECK(low);CHECK(!high);}
TEST("social", showing_previously_unknown_item_can_be_understood){auto w=scene("friendly");auto& s=w.edit_for_test();WorldObject o;o.id=2000;o.owner=o.holder=1;o.place=2;o.kind=ObjectKind::Keepsake;s.social.objects.push_back(o);for(int i=0;i<2;++i)s.actors[i].mind.social.methods[sk(Interaction::ShowItem)]={.9,.4,.9,.8,999};CHECK(!s.actors[1].mind.social.item(2000));w.propose_social_for_test(1,Interaction::ShowItem,2,2000);w.run_seconds(30);CHECK(completions(w,Interaction::ShowItem)==1);CHECK(w.state().actors[1].mind.social.item(2000));CHECK(w.state().actors[1].mind.social.item(2000)->owner_status==Truth::Unknown);}
TEST("social", a_claim_is_a_report_not_a_change_in_ownership){auto w=scene("status");w.run_seconds(120);const auto* memory=w.state().actors[1].mind.social.item(2000);CHECK(memory&&memory->owner_status==Truth::Conflicting);auto& objects=w.state().social.objects;auto it=std::find_if(objects.begin(),objects.end(),[](auto&o){return o.id==2000;});CHECK(it->owner==2);}
TEST("social", learning_item_use_does_not_reveal_hidden_owner){auto w=scene("borrow");auto& s=w.edit_for_test();s.autonomy=false;auto& a=s.actors[0];w.command_for_test(1,Method::Idle,2);auto* m=a.mind.social.item(2000);m->owner=0;m->owner_status=Truth::Unknown;m->holder=1;m->holder_status=Truth::Confirmed;auto it=std::find_if(s.social.objects.begin(),s.social.objects.end(),[](auto&o){return o.id==2000;});it->holder=1;it->owner=3;
    w.use_object_for_test(1,2000);
    w.run_seconds(60);s.autonomy=true;w.run_seconds(30);CHECK(w.state().actors[0].mind.social.item(2000)->owner_status==Truth::Unknown);
}
TEST("social", response_holds_offer_and_known_method_in_shared_context){auto w=scene("friendly");bool saw=false;w.set_thought_logger([&](const Thought& t){if(t.method==Method::Social&&t.detail=="social_accept_specific_proposal"){saw=true;CHECK(t.slots>=3&&t.slots<=12);}});w.run_seconds(30);CHECK(saw);}
TEST("social", interrupted_accepted_contact_keeps_partial_real_experience){auto w=scene("friendly");w.propose_social_for_test(1,Interaction::FriendlyTouch,2);for(int i=0;i<60&&w.state().social.events[0].phase!=SocialPhase::Accepted;++i)w.run_ms(100);CHECK(w.state().social.events[0].phase==SocialPhase::Accepted);w.run_ms(1000);w.withdraw_social_for_test(1);for(auto& a:w.edit_for_test().actors)a.mind.social.methods[0].mastery=0;w.run_seconds(30);CHECK(completions(w,Interaction::FriendlyTouch)==0);auto* e=w.state().actors[0].mind.social.experience(Interaction::FriendlyTouch,2,0,false);CHECK(e&&e->pleasure.count>0&&e->pleasure.mean>0);}
TEST("social", losing_item_during_read_does_not_teach_or_count_completion){auto w=scene("borrow");auto& s=w.edit_for_test();s.autonomy=false;auto& obj=s.social.objects.back();obj.holder=1;w.use_object_for_test(1,2000);w.run_seconds(10);obj.holder=2;w.run_seconds(50);CHECK(completions(w,Interaction::UseItem)==0);CHECK(s.actors[0].completed[std::size_t(Method::UseObject)]==0);CHECK(s.actors[0].mind.social.methods[2].mastery==.55);}
TEST("social", objective_item_unavailable_does_not_reveal_hidden_owner){auto w=scene("borrow");w.edit_for_test().social.objects.back().owner=3;w.run_seconds(120);CHECK(completions(w,Interaction::BorrowItem)==0);CHECK(w.state().actors[0].mind.social.item(2000)->owner==2);bool found=false;for(const auto& e:w.state().social.events)if(e.kind==Interaction::BorrowItem&&e.phase==SocialPhase::Cancelled){found=true;CHECK(e.reason==SocialReason::Unavailable);}CHECK(found);}
TEST("social", friendly_chosen_while_known_pleasant_romance_is_personally_rejected){auto w=scene("personal-boundaries");auto v=w.personal_view(1);auto f=evaluate_social(v.social,Interaction::FriendlyTouch,2,0),r=evaluate_social(v.social,Interaction::RomanticTouch,2,0);CHECK(f.known&&r.known&&r.pleasure>0&&r.moral==1);CHECK(f.score>0&&r.score<0);w.run_seconds(120);CHECK(completions(w,Interaction::FriendlyTouch)>0);CHECK(completions(w,Interaction::RomanticTouch)==0);}
TEST("social", diagnostic_export_does_not_change_personal_knowledge){auto w=scene("borrow");w.run_seconds(120);auto hash=w.hash();auto text=w.social_report_json();CHECK(text.find("world_objects")!=std::string::npos);CHECK(w.hash()==hash);}
TEST("social", book_can_teach_initially_unknown_content_without_scripted_unlock){auto w=scene("borrow-novice");CHECK(w.state().actors[0].mind.social.methods[2].mastery==0);w.run_seconds(3600);CHECK(w.state().actors[0].mind.social.methods[2].mastery>=.6);CHECK(w.state().actors[0].mind.social.item(2000)->uses>2);CHECK(w.state().social.loans.size()==1);CHECK(w.state().social.objects.back().owner==2);w.validate();}
TEST("social", perceived_disapproval_affects_shame_without_automatic_global_reputation){auto w=scene("status");double shame=0;for(int i=0;i<120;++i){w.run_seconds(1);shame=std::max(shame,w.state().actors[0].affect.total[std::size_t(Emotion::Shame)]);}CHECK(shame>.05);CHECK(!w.state().actors[2].mind.social.item(2000));}
