from pathlib import Path
# Single-source declarations. Generated C++ remains part of the source distribution.
types={
'Need': [('double','value','70'),('double','awake_drain','0'),('double','sleep_drain','0'),('double','sleep_gain','0'),('double','critical','10'),('double','activation','35'),('double','target','80'),('bool','enabled','true'),('bool','active','false'),('bool','critical_active','false')],
'Position':[('std::string','kind','"at"'),('Id','place','{}'),('Id','edge','{}'),('Id','from','{}'),('Id','to','{}'),('Minute','started','0'),('Minute','due','0'),('double','base_progress','0'),('double','progress','0')],
'Relation':[('double','affection','0'),('double','trust','.5'),('double','tension','0'),('double','attraction','0'),('bool','affection_high','false'),('bool','tension_high','false'),('Minute','contact_expected','-1')],
'Drive':[('double','intensity','0'),('double','pressure','0')],
'Statement':[('Id','subject','{}'),('std::string','predicate','{}'),('Json','arguments','Object{}'),('bool','polarity','true'),('Minute','valid_from','0'),('Minute','valid_until','-1')],
'Evidence':[('Id','id','{}'),('Statement','statement','{}'),('std::string','kind','"observation"'),('Minute','learned_at','0'),('double','confidence','1'),('Id','source','{}'),('std::vector<Id>','roots','{}'),('double','prior','.5'),('double','half_life','0'),('double','severity','0')],
'Actor':[('Id','id','{}'),('std::string','name','{}'),('Minute','birth_day','-10950'),('Id','account','{}'),('Position','position','{}'),('std::map<std::string,Need>','needs','{}'),('std::map<std::string,double>','traits','{}'),('std::map<std::string,double>','norm_prices','{}'),('std::map<std::string,double>','interests','{}'),('std::map<std::string,double>','repetition','{}'),('std::map<std::string,double>','skills','{}'),('std::set<std::string>','known_methods','{}'),('std::set<std::string>','known_topics','{}'),('std::map<std::string,double>','anger','{}'),('std::map<std::string,Relation>','relations','{}'),('std::map<std::string,Drive>','drives','{}'),('std::vector<Evidence>','beliefs','{}'),('std::vector<Id>','inbox','{}'),('std::map<std::string,bool>','latches','{}'),('double','health','1'),('double','fatigue','0'),('double','pain','0'),('double','impairment','0'),('double','stress','0'),('double','fear','0'),('double','selfesteem','.5'),('double','selfesteem_base','.5'),('double','wellbeing','0'),('double','capacity_kg','15'),('double','base_speed','1'),('double','attention','.8'),('bool','alive','true'),('bool','capable','true'),('bool','heavy_allowed','true'),('Id','active_action','{}'),('Minute','horizon','180'),('std::int64_t','search_width','8'),('std::map<std::string,std::int64_t>','outcome_counts','{}')],
'Place':[('Id','id','{}'),('std::string','name','{}'),('Id','owner','{}'),('bool','private_space','false'),('bool','public_entry','true'),('std::int64_t','capacity','20'),('std::vector<std::vector<Minute>>','open_windows','{{0,1440}}')],
'Edge':[('Id','id','{}'),('Id','from','{}'),('Id','to','{}'),('Minute','minutes','1'),('bool','open','true'),('Id','key','{}')],
'Placement':[('std::string','kind','"at"'),('Id','ref','{}')],
'Item':[('Id','id','{}'),('Id','type','{}'),('Id','owner','{}'),('Placement','placement','{}'),('double','condition','1'),('std::int64_t','version','1'),('std::int64_t','total_units','0'),('std::int64_t','remaining_units','0'),('bool','open','true'),('bool','locked','false'),('Id','key','{}'),('bool','important','false'),('bool','secured','false'),('Id','created_by','"genesis"')],
'Shop':[('Id','id','{}'),('Id','place','{}'),('Id','account','{}'),('std::int64_t','slots','1'),('std::map<Id,Money>','stock','{}')],
'Permission':[('Id','resource','{}'),('Id','authority','{}'),('std::set<Id>','grantees','{}'),('std::set<Id>','denied','{}'),('std::int64_t','version','1')],
'Contract':[('Id','id','{}'),('Id','worker','{}'),('Id','employer_account','{}'),('Id','workplace','{}'),('Money','rate_per_hour','60'),('Money','accrued_numerator','0'),('Minute','next_payout','1440'),('Minute','payout_period','1440'),('std::vector<std::vector<Minute>>','windows','{{480,1020}}')],
'Command':[('Id','actor','{}'),('std::int64_t','sequence','0'),('std::string','type','"A01"'),('Json','args','Object{}'),('std::map<Id,std::int64_t>','expected_versions','{}'),('Id','intent','{}')],
'Receipt':[('std::string','fingerprint','{}'),('Json','request','Object{}'),('Id','actor','{}'),('Id','action','{}'),('std::string','status','"queued"'),('std::string','public_reason','{}'),('std::string','debug_reason','{}'),('Minute','received','0')],
'Reservation':[('Id','id','{}'),('Id','resource','{}'),('Id','action','{}'),('Money','amount','1'),('Money','capacity','1'),('Minute','until','0')],
'Job':[('Id','id','{}'),('Id','recipe','{}'),('Id','creator','{}'),('Id','place','{}'),('Id','target','{}'),('Id','fixture','{}'),('std::vector<Id>','tools','{}'),('std::vector<Id>','materials','{}'),('std::vector<Id>','outputs','{}'),('Minute','worked','0'),('Minute','required','1'),('std::string','status','"paused"'),('Id','active_action','{}'),('double','recorded_loss_kg','0')],
'Proposal':[('Id','id','{}'),('std::int64_t','version','1'),('Id','author','{}'),('std::set<Id>','participants','{}'),('std::set<Id>','signatures','{}'),('Json','terms','Object{}'),('Minute','created','0'),('Minute','expires','0'),('std::string','state','"offered"'),('Id','root','{}'),('bool','executed','false'),('std::vector<Json>','prior_versions','{}')],
'Obligation':[('Id','id','{}'),('Id','root','{}'),('Id','debtor','{}'),('Id','creditor','{}'),('std::string','kind','{}'),('Id','item','{}'),('Id','target','{}'),('Money','amount','0'),('Money','remaining','0'),('Minute','due','0'),('bool','important','false'),('std::string','status','"pending"'),('Minute','fulfilled_at','-1'),('Minute','breached_at','-1'),('std::set<Id>','acknowledged','{}')],
'Action':[('Id','id','{}'),('std::string','type','{}'),('Id','actor','{}'),('std::vector<Id>','participants','{}'),('std::vector<Id>','commands','{}'),('Json','args','Object{}'),('Minute','started','0'),('Minute','due','0'),('Minute','elapsed','0'),('Id','job','{}'),('Id','proposal','{}'),('std::int64_t','proposal_version','0'),('Money','price','0'),('Json','captured','Object{}'),('Id','intent','{}'),('std::set<Id>','entry_observers','{}')],
'RecordVersion':[('std::int64_t','version','1'),('Minute','time','0'),('Json','content','Object{}'),('std::set<Id>','acl','{}'),('bool','public_read','false'),('bool','deleted','false')],
'Record':[('Id','id','{}'),('Id','author','{}'),('std::vector<RecordVersion>','versions','{}')],
'Message':[('Id','id','{}'),('Id','author','{}'),('std::vector<Id>','recipients','{}'),('Json','content','Object{}'),('std::vector<Id>','roots','{}'),('std::string','channel','"speech"'),('Minute','sent','0'),('Minute','deliver_at','0'),('bool','delivered','false'),('std::set<Id>','readers','{}')],
'Event':[('Id','uid','{}'),('std::int64_t','sequence','0'),('Minute','time','0'),('std::string','phase','{}'),('std::string','type','{}'),('Id','cause','{}'),('Id','root','{}'),('std::vector<Id>','participants','{}'),('std::vector<Id>','objects','{}'),('Json','data','Object{}'),('Json','private_data','Object{}'),('std::map<Id,Json>','projections','{}')],
'Appraisal':[('Id','observer','{}'),('Id','target','{}'),('Id','root','{}'),('std::string','type','{}'),('double','trust_delta','0'),('double','tension_delta','0'),('double','stress_delta','0'),('double','anger_delta','0'),('double','esteem_delta','0')],
'External':[('Id','id','{}'),('Minute','at','0'),('std::int64_t','priority','0'),('Id','issuer','"scenario"'),('std::string','kind','{}'),('Json','args','Object{}'),('bool','applied','false')],
'State':[('std::string','version','rules_version'),('std::string','config_hash','{}'),('std::string','profile','"baseline"'),('std::string','seed','"world-seed-1"'),('Minute','time','0'),('std::map<Id,Place>','places','{}'),('std::map<Id,Edge>','edges','{}'),('std::map<Id,Actor>','actors','{}'),('std::map<Id,Item>','items','{}'),('std::map<Id,Money>','accounts','{}'),('std::map<Id,Shop>','shops','{}'),('std::map<Id,Permission>','permissions','{}'),('std::map<Id,Contract>','contracts','{}'),('std::map<Id,Action>','actions','{}'),('std::map<Id,Job>','jobs','{}'),('std::map<Id,Proposal>','proposals','{}'),('std::map<Id,Obligation>','obligations','{}'),('std::map<Id,Record>','records','{}'),('std::map<Id,Message>','messages','{}'),('std::map<Id,Reservation>','reservations','{}'),('std::map<Id,Receipt>','receipts','{}'),('std::vector<Command>','pending','{}'),('std::vector<External>','external','{}'),('std::vector<Event>','ledger','{}'),('std::map<Id,std::int64_t>','event_counters','{}'),('std::set<Id>','delivered_evidence','{}'),('std::map<Id,Appraisal>','appraisal_history','{}'),('std::map<Id,Minute>','positive_cooldowns','{}'),('Money','genesis_money','0'),('Money','external_money','0'),('std::int64_t','next_event_sequence','0')]
}
out=['#pragma once','#include "npc/json.hpp"','namespace npc {']
for name,fields in types.items():
 out.append('struct '+name+' {')
 for typ,field,default in fields: out.append('    '+typ+' '+field+' = '+default+';')
 for const in ('',' const'):
  out.append('    template<class F> void visit(F&& f)'+const+' {')
  for typ,field,default in fields:out.append('        f("'+field+'", '+field+');')
  out.append('    }')
 out.append('};')
out+=['struct TickReport {Minute time; std::size_t events;};','inline Id command_key(const Command& c){return c.actor+"@"+std::to_string(c.sequence);}','}']
Path('include/npc/model.hpp').write_text('\n'.join(out)+'\n')
