#include "test.hpp"
#include "life/world.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
using namespace life;
namespace {
SocialView view(){SocialView v;v.enabled=true;v.self=1;v.partner=2;v.place=2;v.in_conversation=true;v.need_social=.5;v.memory.gender=Gender::Man;v.memory.people={{2,Gender::Man,.7,100}};v.familiarities={{2,.8}};v.memory.norms.fill(0);v.memory.public_romance_disapproval=0;v.memory.public_boasting_disapproval=0;v.memory.expected_attraction={0,1,1};for(auto& k:v.memory.methods)k={.9,.7,.8,.8,100};return v;}
InteractionObservation observation(std::uint64_t id,SocialStage stage,Interaction k=Interaction::FriendlyTouch){InteractionObservation o;o.delivery=id;o.event=id+100;o.kind=k;o.stage=stage;o.other=2;o.at=100;o.initiated=true;return o;}
ItemMemory item(){ItemMemory x;x.id=9;x.owner=2;x.holder=1;x.owner_status=x.holder_status=Truth::Confirmed;x.source=90;x.prestige=.9;return x;}
}
TEST("social_unit", knowing_reward_is_not_an_experienced_reward){auto v=view();CHECK(v.memory.methods[0].expected_pleasure>0);CHECK(v.memory.experiences.empty());auto e=evaluate_social(v,Interaction::FriendlyTouch,2,0);CHECK(e.known&&e.pleasure>0);CHECK(v.memory.experiences.empty());}
TEST("social_unit", unknown_social_method_not_a_candidate){auto v=view();v.memory.methods[0].mastery=.59;auto options=social_choices(v);CHECK(std::none_of(options.begin(),options.end(),[](auto& x){return x.kind==Interaction::FriendlyTouch;}));CHECK(!evaluate_social(v,Interaction::FriendlyTouch,2,0).known);}
TEST("social_unit", pleasant_but_personally_disapproved_stays_pleasant_in_forecast){auto v=view();v.memory.norms[std::size_t(SocialNorm::PersonalRomance)]=1;auto e=evaluate_social(v,Interaction::RomanticTouch,2,0);CHECK(e.known);CHECK(e.pleasure>0);CHECK(e.moral==1);CHECK(std::isfinite(e.score)&&e.score<0);}
TEST("social_unit", no_universal_same_gender_prohibition){auto v=view();auto a=evaluate_social(v,Interaction::RomanticTouch,2,0);v.memory.people[0].gender=Gender::Woman;auto b=evaluate_social(v,Interaction::RomanticTouch,2,0);CHECK(a.score>0);NEAR(a.score,b.score,1e-12);}
TEST("social_unit", friendly_is_not_romantic){auto v=view();auto before=evaluate_social(v,Interaction::FriendlyTouch,2,0);v.memory.norms[4]=1;auto after=evaluate_social(v,Interaction::FriendlyTouch,2,0);NEAR(before.score,after.score,1e-12);CHECK(after.moral==0);}
TEST("social_unit", no_attraction_is_distinct_from_moral_penalty){auto v=view();v.memory.expected_attraction[2]=0;v.need_social=0;auto e=evaluate_social(v,Interaction::RomanticTouch,2,0,true);CHECK(e.moral==0);CHECK(e.pleasure==0);CHECK(e.score<0);}
TEST("social_unit", known_audience_changes_public_evaluation_only){auto v=view();v.memory.public_romance_disapproval=.8;auto a=evaluate_social(v,Interaction::RomanticTouch,2,0);v.known_audience=1;auto b=evaluate_social(v,Interaction::RomanticTouch,2,0);CHECK(b.devaluation>a.devaluation);CHECK(b.score<a.score);}
TEST("social_unit", accept_is_not_completed_pleasure){auto v=view();auto o=observation(1,SocialStage::Accepted);CHECK(v.memory.observe(o,Cognitive{},.5));auto* e=v.memory.experience(o.kind,2,0,false);CHECK(e&&e->accepted==2&&e->pleasure.count==0);}
TEST("social_unit", experienced_negative_result_teaches_from_zero){auto v=view();auto o=observation(1,SocialStage::Completed);o.pleasure=-.8;o.pleasure_observed=true;v.memory.observe(o,Cognitive{},.5);CHECK(v.memory.experience(o.kind,2,0,false)->pleasure.mean<0);}
TEST("social_unit", repeated_result_not_a_second_experience){auto v=view();auto o=observation(1,SocialStage::Completed);o.pleasure=.7;o.pleasure_observed=true;CHECK(v.memory.observe(o,Cognitive{},.5));auto count=v.memory.learned_outcomes;CHECK(!v.memory.observe(o,Cognitive{},.5));CHECK(count==v.memory.learned_outcomes);}
TEST("social_unit", refusal_context_not_spread_to_all_methods){auto v=view();auto baseline=evaluate_social(v,Interaction::FriendlyTouch,2,0);auto o=observation(1,SocialStage::Declined,Interaction::RomanticTouch);o.reason=SocialReason::NotInterested;v.memory.observe(o,Cognitive{},.5);CHECK(v.memory.experience(Interaction::RomanticTouch,2,0,false)->refused==2);CHECK(v.memory.experience(Interaction::FriendlyTouch,2,0,false)==nullptr);NEAR(baseline.score,evaluate_social(v,Interaction::FriendlyTouch,2,0).score,1e-12);}
TEST("social_unit", own_decline_is_not_the_others_rejection){auto v=view();auto o=observation(1,SocialStage::Declined);o.initiated=false;o.reason=SocialReason::NotInterested;v.memory.observe(o,Cognitive{},.5);auto* e=v.memory.experience(o.kind,2,0,false);CHECK(e->issued_boundaries==1);CHECK(e->refused==1&&v.memory.refusals_received==0);}
TEST("social_unit", repeated_request_after_explicit_boundary_creates_pressure){auto v=view();auto decline=observation(1,SocialStage::Declined);decline.initiated=false;decline.reason=SocialReason::NotInterested;v.memory.observe(decline,Cognitive{},.5);auto offer=observation(2,SocialStage::Offer);offer.initiated=false;v.memory.observe(offer,Cognitive{},.5);CHECK(v.memory.pressure_received==1);}
TEST("social_unit", busy_does_not_create_personal_boundary){auto v=view();auto o=observation(1,SocialStage::Declined);o.initiated=false;o.reason=SocialReason::Busy;v.memory.observe(o,Cognitive{},.5);auto x=observation(2,SocialStage::Offer);x.initiated=false;v.memory.observe(x,Cognitive{},.5);CHECK(v.memory.pressure_received==0);}
TEST("social_unit", later_attempt_does_not_erase_old_learning){auto v=view();auto o=observation(1,SocialStage::Declined);o.reason=SocialReason::NotInterested;v.memory.observe(o,Cognitive{},.5);v.now=100;auto before=evaluate_social(v,o.kind,2,0);v.now=3600100;auto after=evaluate_social(v,o.kind,2,0);CHECK(after.repetition<before.repetition);CHECK(after.acceptance==before.acceptance);CHECK(v.memory.experience(o.kind,2,0,false)->refused==2);}
TEST("social_unit", unknown_owner_stays_unknown_after_unknown_report){SocialMemory m;auto x=item();x.owner_status=Truth::Unknown;x.owner=0;m.report_item(x,2,1,0,false);CHECK(m.item(9)->owner_status==Truth::Unknown);}
TEST("social_unit", ownership_is_reported_not_physically_certified){SocialMemory m;m.report_item(item(),2,1,0,false);CHECK(m.item(9)->owner==2);CHECK(m.item(9)->origin==FactOrigin::Reported);CHECK(m.item(9)->claims[0].speaker==2);}
TEST("social_unit", contradictory_reports_preserve_both_sources){SocialMemory m;auto x=item();m.report_item(x,2,1,0,false);x.owner=3;m.report_item(x,4,2,100,false);CHECK(m.item(9)->owner_status==Truth::Conflicting);CHECK(m.item(9)->claims.size()==2);}
TEST("social_unit", repeat_report_same_source_not_duplicated){SocialMemory m;auto x=item();m.report_item(x,2,1,0,false);m.report_item(x,2,1,0,false);CHECK(m.item(9)->claims.size()==1);}
TEST("social_unit", agreement_updates_holder_without_changing_owner){SocialMemory m;auto x=item();m.report_item(x,2,1,0,false);x.holder=2;m.report_item(x,2,2,100,true);CHECK(m.item(9)->owner==2);CHECK(m.item(9)->holder==2);CHECK(m.item(9)->holder_status==Truth::Confirmed);}
TEST("social_unit", claimed_ownership_has_finite_honesty_cost){auto v=view();v.memory.items={item()};auto a=evaluate_social(v,Interaction::ClaimItem,2,9);v.memory.norms[std::size_t(SocialNorm::Honesty)]=1;auto b=evaluate_social(v,Interaction::ClaimItem,2,9);CHECK(a.score>0);CHECK(b.score<0&&std::isfinite(b.score));CHECK(b.moral==1);}
TEST("social_unit", truthful_showing_borrowed_item_is_not_lying){auto v=view();v.memory.items={item()};v.memory.norms[std::size_t(SocialNorm::Honesty)]=1;auto e=evaluate_social(v,Interaction::ShowItem,2,9);CHECK(e.moral==0);}
TEST("social_unit", status_motive_changes_item_value){auto v=view();v.memory.items={item()};v.memory.status_importance=0;auto a=evaluate_social(v,Interaction::ShowItem,2,9);v.memory.status_importance=1;auto b=evaluate_social(v,Interaction::ShowItem,2,9);CHECK(b.score>a.score);}
TEST("social_unit", observed_disapproval_changes_status_prediction){auto v=view();v.memory.items={item()};auto before=evaluate_social(v,Interaction::ShowItem,2,9);for(int n=1;n<=12;++n){auto o=observation(n,SocialStage::Completed,Interaction::ShowItem);o.object=9;o.approval=-.8;o.approval_observed=true;v.memory.observe(o,Cognitive{},.5);}auto after=evaluate_social(v,Interaction::ShowItem,2,9);CHECK(after.status_gain<before.status_gain);}
TEST("social_unit", reading_teaches_content_not_actual_contact_reward){auto v=view();v.memory.methods[2]={.55,0,.5,.4,50};auto o=observation(1,SocialStage::Used,Interaction::UseItem);o.lesson_present=true;o.lesson_kind=Interaction::Compliment;o.lesson={1,.6,.7,.8,90};v.memory.observe(o,Cognitive{},.5);CHECK(v.memory.methods[2].mastery>.55);CHECK(v.memory.methods[2].expected_pleasure==.6);CHECK(v.memory.experience(Interaction::Compliment,2,0,false)==nullptr);}
TEST("social_unit", unknown_object_not_given_free_plan){auto v=view();auto e=evaluate_social(v,Interaction::BorrowItem,2,999);CHECK(!e.known);}
TEST("social_unit", unknown_gender_not_assigned_matching_norm){auto v=view();v.memory.people[0].gender=Gender::Unknown;v.memory.norms[4]=1;auto e=evaluate_social(v,Interaction::RomanticTouch,2,0);CHECK(e.moral==0);}
TEST("social_unit", malformed_social_values_rejected){auto v=view();v.memory.norms[0]=std::numeric_limits<double>::quiet_NaN();THROWS(validate_social_memory(v.memory));}
TEST("social_unit", forecast_repetitions_do_not_modify_memory){auto v=view();for(int i=0;i<100;++i)evaluate_social(v,Interaction::RomanticTouch,2,0);CHECK(v.memory.learned_outcomes==0&&v.memory.processed.empty());}
TEST("social_unit", object_goal_can_make_question_valuable_without_social_deficit){auto v=view();auto x=item();x.owner=0;x.owner_status=Truth::Unknown;v.memory.items={x};v.memory.goal_object=9;v.need_social=0;auto e=evaluate_social(v,Interaction::AskInfo,2,9);CHECK(e.instrumental>.5&&e.score>0);}
TEST("social_unit", receiver_does_not_own_the_speakers_claim){auto v=view();v.self=2;v.partner=1;auto x=item();x.owner=1;v.memory.items={x};v.memory.norms[std::size_t(SocialNorm::Honesty)]=1;auto e=evaluate_social(v,Interaction::ClaimItem,1,9,true);CHECK(e.moral==0);}
TEST("social_unit", ordinary_conversation_considers_multiple_known_people){auto w=World::generate(42,8);auto v=w.personal_view(1);v.place=2;v.known.fill(false);v.known[std::size_t(Method::Talk)]=true;v.need.fill(0);v.need[5]=1;v.perceived_people={2,3};v.social.enabled=false;auto choices=Planner::ideas(v,w.state().random);bool two=false,three=false;for(auto& c:choices){two|=c.partner==2;three|=c.partner==3;}CHECK(two&&three);}
TEST("social_unit", own_promise_norm_changes_return_motivation){auto v=view();v.memory.items={item()};v.memory.norms[std::size_t(SocialNorm::Promise)]=0;auto a=evaluate_social(v,Interaction::ReturnItem,2,9);v.memory.norms[std::size_t(SocialNorm::Promise)]=1;auto b=evaluate_social(v,Interaction::ReturnItem,2,9);CHECK(b.score>a.score);}
TEST("social_unit", observed_thing_is_not_proof_of_ownership){SocialMemory m;auto i=item();i.owner_status=Truth::Unknown;i.owner=0;m.report_item(i,2,11,0,true,FactOrigin::Observed);CHECK(m.item(9)->owner_status==Truth::Unknown);CHECK(m.item(9)->holder==1);}
TEST("social_unit", canceled_delivery_does_not_learn_unobserved_pleasure){auto v=view();auto o=observation(12,SocialStage::Cancelled);o.pleasure=.7;v.memory.observe(o,Cognitive{},.5);CHECK(v.memory.experience(o.kind,2,0,false)->pleasure.count==0);}
TEST("social_unit", object_use_forecast_changes_from_its_own_experience){auto v=view();v.memory.items={item()};auto a=evaluate_social(v,Interaction::UseItem,0,9);for(int j=1;j<=12;++j){auto o=observation(j,SocialStage::Used,Interaction::UseItem);o.other=0;o.object=9;o.pleasure=-.8;o.pleasure_observed=true;v.memory.observe(o,Cognitive{},.5);}auto b=evaluate_social(v,Interaction::UseItem,0,9);CHECK(b.pleasure<a.pleasure&&b.score<a.score);}
TEST("social_unit", contextual_romantic_experience_is_not_multiplied_by_preference_twice){auto v=view();v.memory.expected_attraction[2]=.2;for(int j=1;j<=20;++j){auto o=observation(j,SocialStage::Completed,Interaction::RomanticTouch);o.pleasure=.7;o.pleasure_observed=true;v.memory.observe(o,Cognitive{},.5);}auto b=evaluate_social(v,Interaction::RomanticTouch,2,0);CHECK(b.pleasure>.2);}
TEST("social_unit", property_norm_affects_lending_something_believed_owned_by_a_third_person){auto v=view();v.self=2;auto x=item();x.owner=3;x.holder=2;v.memory.items={x};auto a=evaluate_social(v,Interaction::BorrowItem,1,9,true);v.memory.norms[std::size_t(SocialNorm::Property)]=1;auto b=evaluate_social(v,Interaction::BorrowItem,1,9,true);CHECK(b.moral>a.moral&&b.score<a.score);}
