#include "test.hpp"
#include "life/world.hpp"
#include <algorithm>
#include <filesystem>
using namespace life;
namespace {
World phones(){auto w=World::generate(42,8);w.configure_recovery();auto& s=w.edit_for_test();s.autonomy=false;for(auto& a:s.actors){a.mind.civil.drafts.clear();a.mind.civil.contacts.clear();a.action={};}auto& a=s.actors[0];const auto& b=s.actors[1];auto it=std::find_if(s.social.objects.begin(),s.social.objects.end(),[&](auto& x){return x.id==b.equipment.phone;});a.mind.civil.learn_number(2,it->phone_number,s.next_id++,0);return w;}
Id greeting(World& w){auto& s=w.edit_for_test();return s.actors[0].mind.civil.compose(2,{},s.next_id++,s.now);}
}
TEST("phone", unknown_number_is_not_derived_from_person_id){auto w=phones();auto& s=w.edit_for_test();s.actors[0].mind.civil.contacts.clear();CHECK(!s.actors[0].mind.civil.compose(2,{},s.next_id++,0));CHECK(!w.send_draft_for_test(1,99));}
TEST("phone", sending_requires_own_possessed_phone){auto w=phones();auto id=greeting(w);auto& s=w.edit_for_test();auto& a=s.actors[0];auto it=std::find_if(s.social.objects.begin(),s.social.objects.end(),[&](auto& x){return x.id==a.equipment.phone;});it->holder=2;CHECK(!w.send_draft_for_test(1,id));CHECK(s.civil.messages.empty());}
TEST("phone", send_delivery_read_are_separate_events){auto w=phones();auto id=greeting(w);CHECK(w.send_draft_for_test(1,id));w.run_seconds(30);CHECK(w.state().civil.sends==1);CHECK(w.state().actors[1].mind.civil.inbox.empty());w.run_seconds(2);CHECK(w.state().civil.deliveries==1);CHECK(w.state().civil.reads==0);auto message=w.state().actors[1].mind.civil.inbox.front();CHECK(w.read_message_for_test(2,message));w.run_seconds(20);CHECK(w.state().civil.reads==1);CHECK(!w.read_message_for_test(2,message));}
TEST("phone", sleep_prevents_texting){auto w=phones();auto id=greeting(w);auto& a=w.edit_for_test().actors[0];a.action.method=Method::Sleep;a.action.phase=Phase::Asleep;CHECK(!w.send_draft_for_test(1,id));}
TEST("phone", compatible_work_continues_during_text){auto w=phones();auto& s=w.edit_for_test();s.now=10*3600000;s.next_physical=s.now;for(auto& a:s.actors){a.physical_at=s.now;a.place=a.home;}auto& a=s.actors[0];a.place=5;w.command_for_test(1,Method::Work,5);auto action=a.action.id;CHECK(w.send_draft_for_test(1,greeting(w)));w.run_seconds(32);CHECK(a.action.id==action);CHECK(a.action.method==Method::Work);CHECK(a.economy.work_today>0);CHECK(s.civil.sends==1);}
TEST("phone", cancellation_not_telepathic){auto w=phones();auto& s=w.edit_for_test();auto aid=s.next_id++;MeetingAgreement m{aid,1,2,2,3600000,7200000,false};s.actors[0].appointments.push_back(m);s.actors[1].appointments.push_back(m);w.cancel_meeting_for_test(1,aid);CHECK(s.actors[0].appointments.empty());CHECK(s.actors[1].appointments.size()==1);CHECK(w.send_draft_for_test(1,s.actors[0].mind.civil.drafts.front().id));w.run_seconds(32);CHECK(s.actors[1].appointments.size()==1);CHECK(w.read_message_for_test(2,s.actors[1].mind.civil.inbox.front()));w.run_seconds(20);CHECK(s.actors[1].appointments.empty());}
TEST("phone", send_does_not_directly_update_self_model){auto w=phones();auto x=w.state().actors[0].mind.self.predict(SelfDomain::General);CHECK(w.send_draft_for_test(1,greeting(w)));w.run_seconds(32);auto y=w.state().actors[0].mind.self.predict(SelfDomain::General);NEAR(x.efficacy,y.efficacy,0);CHECK(w.state().actors[0].cog.outcome_published>0);}
TEST("phone", serialization_mid_send_and_unread_message){auto w=phones();CHECK(w.send_draft_for_test(1,greeting(w)));w.run_seconds(12);auto p=(std::filesystem::temp_directory_path()/"life_phone13.save").string();w.save(p);auto b=World::load(p);w.run_seconds(100);b.run_seconds(100);CHECK(w.hash()==b.hash());auto mid=w.state().actors[1].mind.civil.inbox.front();CHECK(w.read_message_for_test(2,mid));CHECK(b.read_message_for_test(2,mid));w.run_seconds(40);b.run_seconds(40);CHECK(w.hash()==b.hash());std::filesystem::remove(p);}
TEST("phone", stranger_cannot_cancel_someone_elses_appointment){auto w=phones();auto& s=w.edit_for_test();auto id=s.next_id++;s.actors[1].appointments.push_back({id,2,3,2,100000,200000,false});LetterContent letter;letter.kind=LetterKind::CancelMeeting;letter.appointment=id;auto draft=s.actors[0].mind.civil.compose(2,letter,s.next_id++,0);CHECK(!w.send_draft_for_test(1,draft));CHECK(s.actors[1].appointments.size()==1);}
TEST("phone", delivered_salary_does_not_become_knowledge_until_read_and_processed){
 auto w=phones();auto& s=w.edit_for_test();Information info;info.id=s.next_id++;info.subject=1;info.kind=NewsKind::Employment;info.resource_present=true;info.resource={info.id,1,0,0,ResourceKind::IncomeHourly,40,1,0,false};s.actors[0].mind.social.community.receive(info,0,s.next_id++,0);
 LetterContent letter;letter.kind=LetterKind::Information;letter.information=info;
 auto draft=s.actors[0].mind.civil.compose(2,letter,info.id,0);CHECK(w.send_draft_for_test(1,draft));w.run_seconds(32);CHECK(!s.actors[1].mind.social.community.resources.assess(1,s.now).hourly);
 CHECK(w.read_message_for_test(2,s.actors[1].mind.civil.inbox.front()));w.run_seconds(20);CHECK(!s.actors[1].mind.social.community.resources.assess(1,s.now).hourly);
 s.autonomy=true;w.run_seconds(90);auto heard=s.actors[1].mind.social.community.resources.assess(1,s.now);CHECK(heard.hourly);NEAR(*heard.hourly,40,0);
}
TEST("phone", interrupted_text_does_not_send){auto w=phones();CHECK(w.send_draft_for_test(1,greeting(w)));w.run_seconds(10);auto& a=w.edit_for_test().actors[0];a.action.id=w.edit_for_test().next_id++;a.action.method=Method::Sleep;a.action.phase=Phase::Asleep;a.action.started=w.state().now;a.action.destination=a.place;a.action.end=w.state().now+3600000;a.action.next_window=w.state().now+300000;w.run_seconds(22);CHECK(w.state().civil.sends==0);CHECK(!a.equipment.side_action);}
TEST("phone", worker_count_and_logging_do_not_change_recovery_state){auto a=World::generate(42,8);a.configure_recovery();auto b=a;a.set_workers(1,4);b.set_workers(4,2);std::uint64_t records=0;b.set_logger([&](const EventLog&){++records;});b.set_thought_logger([&](const Thought& t){CHECK(!thought_json(t).empty());});a.run_seconds(1800);b.run_seconds(1800);CHECK(a.hash()==b.hash());CHECK(records>0);}
TEST("phone", phone_cannot_overlap_a_pending_joint_interaction){auto w=phones();auto draft=greeting(w);w.edit_for_test().actors[0].mind.social.active_event=123;CHECK(!w.send_draft_for_test(1,draft));}
TEST("phone", resource_forecast_and_execution_agree_under_conversation_load){auto w=phones();auto& s=w.edit_for_test();auto& a=s.actors[0];a.action.method=Method::Study;a.action.phase=Phase::Running;a.conversation.id=10;a.conversation.partner=2;CHECK(!w.personal_view(1).civil.can_text);CHECK(!w.send_draft_for_test(1,greeting(w)));}
TEST("phone", remote_contact_preserves_last_physically_observed_location){Mind mind;CHECK(mind.experience_contact(2,1,0,30,.2,5));CHECK(mind.experience_contact(2,2,1000,20,.2,0));CHECK(mind.relation(2)->last_known_place==5);CHECK(mind.relation(2)->last_seen==0);CHECK(mind.relation(2)->last_contact==1000);}
