#include "test.hpp"
#include "life/world.hpp"
#include "attention.hpp"
#include <filesystem>
using namespace life;
TEST("cognition", real_thoughts_are_published_after_logical_work){auto w=World::generate(42,8);std::vector<Thought> ts;w.set_thought_logger([&](auto& t){ts.push_back(t);});w.run_ms(100);CHECK(ts.empty());w.run_seconds(120);CHECK(!ts.empty());bool intent=false;for(const auto& t:ts){if(t.kind!=ThoughtKind::Notice)CHECK(t.time>t.started);if(t.kind==ThoughtKind::Intent)intent=true;}CHECK(intent);}
TEST("cognition", interpretation_exact_numeric_example){SubjectiveNeed p;p.prior=.2;p.prior_quality=.6;p.prior_source=3;auto s=interpret_need(p,.4992,.8,4,100);NEAR(s.mean,.4176,1e-12);NEAR(s.confidence,.56064,1e-12);}
TEST("cognition", contradictory_interpretation_is_not_average){SubjectiveNeed p;p.prior=.1;p.prior_quality=.9;p.prior_source=2;CHECK(interpret_need(p,.9,.9,3,100).status==Truth::Conflicting);}
TEST("cognition", repeated_interpretation_does_not_reinforce_itself){SubjectiveNeed p;p.prior=.2;p.prior_quality=.6;p.prior_source=3;auto x=interpret_need(p,.4992,.8,4,100);auto y=interpret_need(x,.4992,.8,4,100);CHECK(x.mean==y.mean);CHECK(x.confidence==y.confidence);}
TEST("cognition", signed_forecast_reduces_action_value){auto w=World::generate(42,8);auto v=w.personal_view(1);v.need.fill(0);v.need[5]=v.need[10]=1;PlanOption p{Method::Talk,2,0,1};v.forecasts[6][10]=0;auto x=Planner::forecast(v,p);v.forecasts[6][10]=-.8;auto y=Planner::forecast(v,p);CHECK(y.score<x.score);}
TEST("cognition", candidate_top32_reserves_emergency){std::vector<AttentionTopic> x;for(unsigned j=1;j<=60;++j){AttentionTopic t;t.id=j;t.priority=double(j)/100;t.expires=10000;t.revision=1;x.push_back(t);}x[0].emergency=true;x[0].urgency=1;auto a=bounded_topics(x,0,2);CHECK(a.size()==32);CHECK(a[0].id==1);CHECK(a[1].id==2);}
TEST("cognition", sleep_has_no_cognitive_credit){auto w=World::generate(42,8);auto& s=w.edit_for_test();s.autonomy=false;s.actors[0].body.sleep=.8;w.command_for_test(1,Method::Sleep,s.actors[0].home);w.run_seconds(121);CHECK(w.state().actors[0].action.phase==Phase::Asleep);auto before=w.state().actors[0].cog.completed_ops;w.edit_for_test().autonomy=true;w.run_seconds(60);CHECK(w.state().actors[0].cog.completed_ops==before);}
TEST("cognition", serialized_mid_operation_has_same_future){auto a=World::generate(42,8);a.run_ms(2111);auto file=(std::filesystem::temp_directory_path()/"cog-mid.save").string();a.save(file);auto b=World::load(file);CHECK(a.hash()==b.hash());a.run_ms(117889);b.run_ms(117889);CHECK(a.hash()==b.hash());std::filesystem::remove(file);}
TEST("cognition", logger_is_observer_not_generator){auto a=World::generate(42,8),b=a;std::uint64_t count=0;b.set_thought_logger([&](auto&){++count;});a.run_seconds(600);b.run_seconds(600);CHECK(count>0);CHECK(a.hash()==b.hash());}
TEST("cognition", threaded_chunks_preserve_full_world){auto a=World::generate(42,8),b=a,c=a;a.set_workers(1,1);b.set_workers(2,2);c.set_workers(4,17);a.run_seconds(600);b.run_seconds(600);c.run_seconds(600);CHECK(a.hash()==b.hash());CHECK(a.hash()==c.hash());}
TEST("cognition", no_forecast_learning_without_execution){auto w=World::generate(42,8);auto n=w.state().actors[0].mind.learning.episodes;w.run_seconds(10);CHECK(w.state().actors[0].cog.counts[std::size_t(ThoughtKind::Forecast)]>0);CHECK(w.state().actors[0].mind.learning.episodes==n);}
TEST("cognition", unknown_rule_does_not_create_named_assessment){auto w=World::generate(42,8);w.edit_for_test().actors[0].mind.knowledge.mastery.clear();w.run_seconds(60);CHECK(w.state().actors[0].cog.counts[std::size_t(ThoughtKind::Interpret)]==0);CHECK(w.state().actors[0].cog.counts[std::size_t(ThoughtKind::Question)]>0);}
TEST("cognition", unknown_method_is_never_forecast){auto w=World::generate(42,8);w.edit_for_test().actors[0].mind.known.fill(false);bool any=false;w.set_thought_logger([&](auto& t){if(t.actor==1&&t.kind==ThoughtKind::Forecast)any=true;});w.run_seconds(60);CHECK(!any);}
TEST("cognition", thought_provenance_links_to_real_forecast){auto w=World::generate(42,8);std::map<std::pair<Id,std::uint64_t>,Thought> ts;int checked=0;w.set_thought_logger([&](auto& t){if(t.kind==ThoughtKind::Intent&&t.method!=Method::Idle){auto it=ts.find({t.actor,t.basis});CHECK(it!=ts.end());CHECK(it->second.kind==ThoughtKind::Forecast);CHECK(it->second.time<=t.time);CHECK(it->second.method==t.method);++checked;}ts[{t.actor,t.id}]=t;});w.run_seconds(600);CHECK(checked>0);}
TEST("cognition", observation_before_commit_makes_operation_stale){auto w=World::generate(42,8);w.run_ms(2050);auto& a=w.edit_for_test().actors[0];CHECK(a.cog.operation!=Operation::None);auto count=a.cog.stale_ops;++a.mind.version;a.mind.believed_money=1;w.run_ms(500);CHECK(w.state().actors[0].cog.stale_ops>count);}
TEST("cognition", changed_other_persons_private_state_is_not_telepathy){auto a=World::generate(42,8),b=a;b.edit_for_test().actors[7].mind.cognition.base[3]=.1;std::vector<std::string>x,y;a.set_thought_logger([&](auto& t){if(t.actor==1)x.push_back(thought_json(t));});b.set_thought_logger([&](auto& t){if(t.actor==1)y.push_back(thought_json(t));});a.run_seconds(10);b.run_seconds(10);CHECK(x==y);}
TEST("cognition", hidden_remote_food_same_thoughts){auto a=World::generate(42,8),b=a;b.edit_for_test().places[2].food-=1;b.edit_for_test().ledger.initial_food-=1;std::vector<std::string>x,y;a.set_thought_logger([&](auto& t){if(t.actor==1)x.push_back(thought_json(t));});b.set_thought_logger([&](auto& t){if(t.actor==1)y.push_back(thought_json(t));});a.run_seconds(10);b.run_seconds(10);CHECK(x==y);}
TEST("cognition", subsecond_split_calls_do_not_change_history){auto a=World::generate(42,8),b=a;a.run_ms(60000);for(unsigned i=0;i<600;++i)b.run_ms(100);CHECK(a.hash()==b.hash());}
TEST("cognition", variable_wall_frames_30_and_144_preserve_world){auto a=World::generate(42,8),b=a;Tick end=10000;for(Tick frame=1;a.state().now<end;++frame)a.run_ms(std::uint64_t(std::min(end,frame*1000/30)-a.state().now));for(Tick frame=1;b.state().now<end;++frame)b.run_ms(std::uint64_t(std::min(end,frame*1000/144)-b.state().now));CHECK(a.hash()==b.hash());}
TEST("cognition", no_early_completions_during_initial_rebuild){auto w=World::generate(42,8);w.run_ms(500);for(const auto& a:w.state().actors){CHECK(a.cog.completed_ops==0);CHECK(a.cog.rebuild_until>0);}}
TEST("cognition", per_episode_budget_is_not_reset_by_notifications){auto w=World::generate(42,8);w.run_ms(2050);auto episode=w.state().actors[0].cog.episode;auto spent=w.state().actors[0].cog.spent;++w.edit_for_test().actors[0].mind.version;w.run_ms(250);const auto& c=w.state().actors[0].cog;CHECK(c.episode==episode);CHECK(c.spent>=spent);CHECK(c.spent+c.budget<=32);}
TEST("cognition", candidate_expiration_does_not_keep_sensory_focus){AttentionTopic a;a.id=1;a.expires=100;AttentionTopic b=a;b.id=2;b.expires=200;auto x=bounded_topics(std::array{a,b},100,1);CHECK(x.size()==1&&x[0].id==2);}
TEST("cognition", negative_previous_q_zero_is_trainable){Learning l;Episode e;e.id=1;e.time=0;e.method=Method::Talk;e.observed=1u<<5;e.outcome[5]=-.4;CHECK(l.observe(e,Cognitive{},.5));CHECK(l.q[6][5].mean<0);}
TEST("cognition", duplicate_actual_episode_not_reinforced){Learning l;Episode e;e.id=1;e.time=0;e.method=Method::Talk;e.observed=1u<<5;e.outcome[5]=-.4;CHECK(l.observe(e,Cognitive{},.5));const auto q=l.q[6][5].mean;CHECK(!l.observe(e,Cognitive{},.5));CHECK(q==l.q[6][5].mean);}
TEST("cognition", no_automatic_person_identification){auto w=World::generate(42,8);w.edit_for_test().actors[0].place=w.edit_for_test().actors[1].place=2;auto v=w.personal_view(1);CHECK(v.perceived_people.empty());w.run_seconds(1);CHECK(w.state().actors[0].cog.counts[std::size_t(ThoughtKind::Recall)]==0);}
TEST("cognition", save_rejects_corrupt_cognitive_work){auto w=World::generate(42,8);w.edit_for_test().actors[0].cog.work=2;THROWS(w.validate());}
TEST("cognition", focus_does_not_destroy_travel){auto w=World::generate(42,8);w.run_seconds(10);auto path=w.state().actors[0].action.path;auto id=w.state().actors[0].action.id;CHECK(w.state().actors[0].action.phase==Phase::Travel);w.run_seconds(20);CHECK(w.state().actors[0].action.id==id);CHECK(w.state().actors[0].action.path==path);}
TEST("cognition", method_forecast_can_value_delayed_income){auto w=World::generate(42,8);auto v=w.personal_view(1);v.need.fill(0);v.need[0]=1;v.food=0;v.money=0;auto d=Planner::forecast(v,{Method::Work,5,0,1});CHECK(d.score>0);CHECK(v.money==0);}
TEST("cognition", forecast_reads_only_personal_snapshot_across_worker_counts){auto w=World::generate(42,8);auto v=w.personal_view(1);v.need[4]=.5;std::vector<std::pair<PersonalView,PlanOption>> jobs;for(int i=0;i<32;++i)jobs.push_back({v,{Method::Leisure,2,0,.5}});ForecastWorkers a(1),b(4);auto x=a.evaluate(jobs,1),y=b.evaluate(jobs,17);CHECK(x.size()==y.size());for(std::size_t i=0;i<x.size();++i){CHECK(x[i].score==y[i].score);CHECK(x[i].path==y[i].path);}}
TEST("cognition", invalid_worker_parameters_rejected){THROWS(ForecastWorkers(0));THROWS(ForecastWorkers(33));auto w=World::generate(42,8);THROWS(w.set_workers(1,0));}
namespace {
World refusal_fixture(double bias){
 auto w=World::generate(42,8);auto& s=w.edit_for_test();s.autonomy=false;
 s.actors[0].place=s.actors[1].place=5;s.places[4].services|=service(Method::Talk);
 s.actors[0].social=.1;s.actors[0].cog.rejection_bias=bias;
 w.command_for_test(2,Method::Work,5);w.command_for_test(1,Method::Talk,5);
 s.autonomy=true;return w;
}
}
TEST("cognition", actual_busy_reply_has_timed_subjective_interpretation){auto w=refusal_fixture(.2);std::vector<Thought> ts;w.set_thought_logger([&](auto& t){if(t.actor==1&&t.kind==ThoughtKind::Reply)ts.push_back(t);});w.run_seconds(10);CHECK(ts.size()==1);CHECK(ts[0].time>ts[0].started);CHECK(ts[0].detail.find("занятости")!=std::string::npos);CHECK(w.state().actors[0].cog.contacts.size()==1);}
TEST("cognition", same_busy_reply_different_interpretations){auto a=refusal_fixture(.1),b=refusal_fixture(.9);a.run_seconds(10);b.run_seconds(10);CHECK(a.state().actors[0].cog.contacts.size()==1);CHECK(b.state().actors[0].cog.contacts[0].unpleasantness>a.state().actors[0].cog.contacts[0].unpleasantness);}
TEST("cognition", forecast_refusal_not_recorded_as_actual_reply){auto w=World::generate(42,8);w.run_seconds(60);CHECK(w.state().actors[0].cog.contacts.empty());}
TEST("cognition", no_automatic_shame_from_hidden_audience){auto a=World::generate(42,8),b=a;b.edit_for_test().actors[7].place=6;a.run_seconds(1);b.run_seconds(1);CHECK(a.state().actors[0].affect.total[8]==b.state().actors[0].affect.total[8]);}
TEST("cognition", workers_preserve_thought_content_and_times){auto a=World::generate(42,8),b=a;b.set_workers(4,2);std::vector<std::string>x,y;a.set_thought_logger([&](auto&t){x.push_back(thought_json(t));});b.set_thought_logger([&](auto&t){y.push_back(thought_json(t));});a.run_seconds(120);b.run_seconds(120);CHECK(x==y);}
TEST("cognition", known_zero_reading_is_not_unknown){SubjectiveNeed p;auto r=interpret_need(p,0,.8,1,0);CHECK(r.status==Truth::Confirmed);CHECK(r.mean==0);}
TEST("cognition", no_evidence_stays_unknown){SubjectiveNeed p;auto r=interpret_need(p,.5,0,1,0);CHECK(r.status==Truth::Unknown);}
TEST("cognition", strong_sleep_signal_does_not_wake_sleep){auto w=World::generate(42,8);auto&s=w.edit_for_test();s.autonomy=false;s.actors[0].body.sleep=.9;w.command_for_test(1,Method::Sleep,s.actors[0].home);w.run_seconds(600);CHECK(w.state().actors[0].action.phase==Phase::Asleep);}
TEST("cognition", obsolete_current_path_cannot_be_executed){auto w=World::generate(42,8);w.run_ms(2800);auto& a=w.edit_for_test().actors[0];a.place=1;++a.mind.version;++a.cog.situation_version;w.run_seconds(120);w.validate();CHECK(w.state().actors[0].alive);}
TEST("cognition", completed_thoughts_and_stale_attempts_accounted){auto w=World::generate(42,8);w.run_seconds(120);for(const auto&a:w.state().actors){const auto& c=a.cog;CHECK(c.completed_ops+c.stale_ops<=c.operation_starts);CHECK(c.operation_starts-c.completed_ops-c.stale_ops<2);}}
TEST("cognition", actual_satisfaction_invalidates_old_need_estimate){auto w=World::generate(42,8);auto& s=w.edit_for_test();s.autonomy=false;auto& n=s.actors[0].cog.needs[0];n.status=Truth::Confirmed;n.mean=.95;n.confidence=.9;n.source=1;w.command_for_test(1,Method::Eat,s.actors[0].home);w.run_seconds(91);CHECK(w.state().actors[0].cog.needs[0].status==Truth::Unknown);}
TEST("cognition", forecast_text_has_russian_action_name){Thought t;t.kind=ThoughtKind::Forecast;t.method=Method::Leisure;t.value=.2;CHECK(thought_text(t).find("досуг")!=std::string::npos);}
TEST("cognition", observed_acceptance_updates_contact_without_fake_satisfaction){
 auto w=World::generate(42,8);auto& s=w.edit_for_test();s.autonomy=false;s.actors[0].place=s.actors[1].place=2;s.actors[0].social=s.actors[1].social=.3;
 w.command_for_test(1,Method::Talk,2);CHECK(s.actors[0].action.partner==2);s.autonomy=true;w.run_seconds(10);
 auto it=std::find_if(w.state().actors[0].cog.contacts.begin(),w.state().actors[0].cog.contacts.end(),[](auto& m){return m.person==2;});
 CHECK(it!=w.state().actors[0].cog.contacts.end());CHECK(it->accepted==2);CHECK(w.state().actors[0].completed[std::size_t(Method::Talk)]==0);
}
TEST("cognition", idle_without_forecast_does_not_claim_an_invented_basis){Thought t;t.kind=ThoughtKind::Intent;t.method=Method::Idle;t.basis=0;CHECK(thought_text(t).find("завершённый прогноз 0")==std::string::npos);}
TEST("cognition", recognition_text_describes_recognized_person_not_an_action){Thought t;t.kind=ThoughtKind::Recall;t.method=Method::Talk;t.person=2;t.origin=Origin::Observed;t.detail="знакомый_образ_после_наблюдения";CHECK(thought_text(t).find("Распознал")!=std::string::npos);}
TEST("cognition", processing_speed_changes_logical_thought_latency){
 auto latency=[](double speed){auto w=World::generate(42,8);w.edit_for_test().actors[0].mind.cognition.base[4]=speed;Tick first=0;w.set_thought_logger([&](const Thought&t){if(t.actor==1&&t.kind==ThoughtKind::Intent&&!first)first=t.time;});w.run_seconds(20);return first;};
 const Tick slow=latency(.1),fast=latency(.9);CHECK(slow>0&&fast>0);CHECK(fast<slow);
}
TEST("cognition", forecast_trace_exposes_target_and_cost_components){auto w=World::generate(42,8);bool checked=false;w.set_thought_logger([&](const Thought&t){if(t.kind==ThoughtKind::Forecast){const auto row=thought_json(t);CHECK(row.find("\"destination\":")!=std::string::npos);CHECK(row.find("\"moral_cost\":")!=std::string::npos);checked=true;}});w.run_seconds(10);CHECK(checked);}
